# Site settings
title: "Mohit Sinha"
description: "Software Developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mohit Sinha"
resume_title:                   "Software Developer"
resume_contact_email:           "mohitsinha.it@gmail.com"
resume_contact_telephone:       "+91-7405677183"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"
resume_header_contact_info: "Powai, Mumbai | +91-7405677183 | mohitsinha.it@gmail.com"
resume_header_intro: >
  <p>I am a software developer who is proficient in Java & Spring related stack to create microservices.
  I also know Machine Learning, SailsJS, AngularJS, Django</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mohitsinha"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://in.linkedin.com/in/sinhamohit"
  # resume_instagram_url:         "insert your Instagram URL here"
#  resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
